Repository scania/corporate-ui, pull requests merged in 2018-11, with the labels that each got.

#371 PANELS: Restored background color - Shifted font declarations.
  src/global/less/corporate-ui/panels-wells.less
Labels: Improvement

#365 file upload component
  demo/examples/file-upload.html
  src/components/file-upload/comment.md
  src/components/file-upload/file-icon/comment.md
  src/components/file-upload/file-icon/index.jade
  src/components/file-upload/file-icon/script.ts
  src/components/file-upload/file-icon/style.less
  src/components/file-upload/file-icon/template.html
  src/components/file-upload/file-icon/variations/1/comment.md
  src/components/file-upload/file-icon/variations/1/demo.html
  src/components/file-upload/file-icon/variations/1/index.jade
  src/components/file-upload/file-icon/variations/1/script.ts
  src/components/file-upload/file-icon/variations/1/style.less
  src/components/file-upload/file-icon/variations/1/template.html
  src/components/file-upload/index.jade
  src/components/file-upload/script.ts
  src/components/file-upload/style.less
  src/components/file-upload/template.html
  src/components/file-upload/variations/1/comment.md
  src/components/file-upload/variations/1/demo.html
  src/components/file-upload/variations/1/index.jade
  src/components/file-upload/variations/1/script.ts
  src/components/file-upload/variations/1/style.less
  src/components/file-upload/variations/1/template.html
  src/components/progress-bar/comment.md
  src/components/progress-bar/index.jade
  src/components/progress-bar/script.ts
  src/components/progress-bar/style.less
  src/components/progress-bar/template.html
  src/components/progress-bar/variations/1/comment.md
  src/components/progress-bar/variations/1/demo.html
  src/components/progress-bar/variations/1/index.jade
  src/components/progress-bar/variations/1/script.ts
  src/components/progress-bar/variations/1/style.less
  src/components/progress-bar/variations/1/template.html
Labels: New Feature

#374 Improvement/select2 table fix
  src/global/less/corporate-ui/custom-classes/select2.less
  src/global/less/corporate-ui/tables.less
Labels: Improvement

#364 Temporary Alignment Fix for text-center in Bootstrap 4 Cards
  src/global/less/corporate-ui/bootstrap-4/bootstrap4-snippets.less
Labels: Improvement

#375 Improvement/select2 table fix
  src/global/less/corporate-ui/custom-classes/select2.less
Labels: Improvement

#380 Fixes for labels on dark background
  src/global/less/corporate-ui/custom-classes/checkboxes.less
Labels: Bug

#379 Issue with main-nav in IE when using data init
  demo/examples/angular-basic-template.html
  demo/examples/angular-navigation.html
  demo/examples/more-dynamic.html
  demo/examples/more-dynamic2.html
  demo/examples/new-structure.html
  src/components/main-navigation/template.html
  src/components/navbar/nav-item/script.ts
  src/components/navbar/nav-item/template.html
Labels: Bug

#362 Modal backdrop z-index and mobile margins
  src/components/corporate-header/style.less
  src/global/less/corporate-ui/modal.less
  src/global/less/corporate-ui/typography.less
Labels: Improvement

#382 Bootstrap scripts not stable in ie
  src/components/main-navigation/style.less
  src/global/ts/core.ts
Labels: Bug, Improvement

#391 Improvements/input fields redesign
  src/global/less/corporate-ui/custom-classes/select2.less
  src/global/less/corporate-ui/forms.less
  src/global/less/corporate-ui/input-groups.less
  src/global/less/corporate-ui/mixins.less
  src/global/less/corporate-ui/panels-wells.less
  src/global/less/corporate-ui/tables.less
  src/global/less/corporate-ui/variables.less
Labels: Improvement

#368 Project tasks cleanup
  gulpfile.js
  package.json
  server.js
Labels: Improvement

#392 Improvements/input fields redesign
  src/global/less/corporate-ui/custom-classes/select2.less
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#384 Added fixes for Modals Article with scroll
  src/global/less/corporate-ui/modal.less
  src/global/less/corporate-ui/navigation.less
  src/global/less/corporate-ui/typography.less
Labels: Improvement

#390 Login improvements
  src/components/login/comment.md
  src/components/login/style.less
  src/components/login/template.html
Labels: Improvement

#386 Styled Bootstrap .help-block and added .alert-primary
  src/global/less/corporate-ui/alerts.less
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#389 Hamburger menu not working as expected
  demo/examples/more-dynamic2.html
  src/components/corporate-header/index.jade
  src/components/corporate-header/script.ts
  src/components/corporate-header/style.less
  src/components/corporate-header/template.html
  src/components/fullscreen/template.html
  src/components/main-navigation/script.ts
  src/components/navbar/nav-item/script.ts
  src/components/navbar/nav-item/template.html
  src/global/ts/core.ts
Labels: Bug

#395 Corporate-footer copyright text not being correctly styled in APP
  src/components/corporate-footer/style.less
Labels: Bug

#399 Main-nav new variation
  demo/examples/more-dynamic2.html
  src/components/main-navigation/index.jade
  src/components/main-navigation/script.ts
  src/components/main-navigation/variations/2/comment.md
  src/components/main-navigation/variations/2/demo.html
  src/components/main-navigation/variations/2/index.jade
  src/components/main-navigation/variations/2/script.ts
  src/components/main-navigation/variations/2/style.less
  src/components/main-navigation/variations/2/template.html
Labels: New Feature

#394 Simplify nav-item props when used in component
  src/components/corporate-header/template.html
  src/components/main-navigation/template.html
  src/components/navbar/nav-item/script.ts
Labels: Improvement

#396 redesign of forms
  src/global/less/corporate-ui/custom-classes/select2.less
  src/global/less/corporate-ui/forms.less
  src/global/less/corporate-ui/mixins.less
Labels: Bug, Improvement

#400 Fix for server runtime error
  gulpfile.js
Labels: Bug

#402 Fixed so that site-name is centered in the corporate header below 992px
  src/global/less/corporate-ui/navigation.less
Labels: Improvement

#404 Improvement/input groups border radius
  src/global/less/corporate-ui/forms.less
  src/global/less/corporate-ui/input-groups.less
Labels: Improvement

#401 Fine adjustments for Modals
  src/global/less/corporate-ui/modal.less
Labels: Improvement

#403 Changed item binding in main-nav
  demo/examples/more-dynamic2.html
  src/components/main-navigation/script.ts
  src/components/main-navigation/template.html
Labels: Improvement

#408 Small fixes for help-block and cookie message.
  .gitignore
  package.json
  src/components/cookie-message/style.less
  src/components/cookie-message/template.html
  src/global/less/corporate-ui/forms.less
  src/global/ts/core.ts
Labels: Improvement

#410 Improvement/height for input group
  demo/examples/Bootstrap/forms.html
  src/global/less/corporate-ui/custom-classes/buttons.less
  src/global/less/corporate-ui/custom-classes/checkboxes.less
  src/global/less/corporate-ui/custom-classes/select2.less
  src/global/less/corporate-ui/forms.less
  src/global/less/corporate-ui/input-groups.less
  src/global/less/corporate-ui/mixins.less
  src/global/less/corporate-ui/variables.less
Labels: Improvement
