Repository scania/corporate-ui, pull requests merged in 2018-08, with the labels that each got.

#111 Fix for more item incorrect with sub nav
  src/components/main-navigation/script.ts
Labels: Bug, Improvement

#109 Improved more item on scroll
  src/components/main-navigation/script.ts
  src/components/main-navigation/style.less
Labels: Improvement

#106 tables border color change from transparent to primary around thead
  src/global/less/corporate-ui/tables.less
Labels: Improvement

#126 Fix for the issue with apply brand function in IE
  src/global/ts/core.ts
Labels: Bug

#124 checkbox and radiobuttons inside input-group
  demo/examples/Bootstrap/forms.html
  src/global/less/corporate-ui.less
  src/global/less/corporate-ui/input-groups.less
Labels: Improvement

#125 Added better support for table-hover table-striped and table-panel improvements
  demo/examples/Bootstrap/table.html
  src/global/less/corporate-ui/mixins.less
  src/global/less/corporate-ui/tables.less
Labels: Bug, Improvement

#134 Checkbox/Radio overflow problem
  demo/examples/Bootstrap/forms.html
  src/global/less/corporate-ui/forms.less
Labels: Bug

#131 removed custom select
  demo/examples/Bootstrap/forms.html
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#138 Fixes for styling of More...drop down menu options
  src/components/main-navigation/style.less
Labels: Improvement

#139 Update version number
  package.json
Labels: Improvement

#137 Removed dublicated code and some clean up in less files
  src/global/less/corporate-ui/core.less
  src/global/less/corporate-ui/custom-classes/index.less
  src/global/less/corporate-ui/custom-classes/list-table.less
  src/global/less/corporate-ui/custom-classes/lists.less
  src/global/less/corporate-ui/custom-classes/panels-wells.less
  src/global/less/corporate-ui/panels-wells.less
Labels: Improvement

#143 Loading components dynamicaly is broken
  src/global/ts/core.ts
Labels: Breaking, Bug

#152 Version number
  package.json
Labels: Improvement

#156 table borderless added
  src/global/less/corporate-ui/mixins.less
  src/global/less/corporate-ui/tables.less
Labels: Improvement

#144 table-condensed font-family changed
  src/global/less/corporate-ui/tables.less
Labels: Bug, Improvement

#154 table-lg added
  demo/examples/Bootstrap/table.html
  src/global/less/corporate-ui/custom-classes/tables.less
Labels: Improvement, New Feature

#155 Updated styling for Progress Bar
  src/global/less/corporate-ui/progressbars.less
Labels: Improvement

#135 Add releases info page
  demo/examples/gh-releases.html
Labels: Improvement, New Feature

#161 dropdown menu in corporate-fotter improvement
  src/components/corporate-footer/style.less
Labels: Improvement

#141 Fixed left indicator for Active item in mobile navigation.
  src/components/main-navigation/style.less
Labels: Improvement

#136 Fox for bs auto data-toggle feature
  src/global/ts/core.ts
Labels: Bug

#162 typography fixes font sizes and font-family changes
  src/global/less/corporate-ui/badges-labels.less
  src/global/less/corporate-ui/custom-classes/page-header.less
  src/global/less/corporate-ui/forms.less
  src/global/less/corporate-ui/panels-wells.less
  src/global/less/corporate-ui/tables.less
  src/global/less/corporate-ui/typography.less
  src/global/less/corporate-ui/variables.less
Labels: Improvement, Major change

#164 panel h3 and h4 styling changed
  src/global/less/corporate-ui/panels-wells.less
Labels: Improvement
