Repository scania/corporate-ui, pull requests merged in 2018-06, with the labels that each got.

#32 Changes for overflow in Firefox on inline checkboxes.
  src/less/corporate-ui/forms.less
Labels: Improvement

#31 panel border color change
  src/less/corporate-ui/mixins.less
  src/less/corporate-ui/panels-wells.less
  src/views/template/Bootstrap/panels.html
Labels: Improvement

#33 Small fixes and added callouts for documentation
  src/less/corporate-ui/custom-classes/alert.less
  src/less/corporate-ui/custom-classes/tables.less
Labels: Improvement

#35 Problems with nested panels not getting a correct styling
  src/less/corporate-ui/panels-wells.less
  src/views/template/Bootstrap/panels.html
Labels: Improvement

#34 Correct font attributes for Footer
  src/views/component/Navigation/corporate-footer/style.less
Labels: Improvement

#42 border-color changes for tables
  src/less/corporate-ui/tables.less
Labels: Improvement

#48 c social media component added
  src/views/component/Bootstrap/navbar/nav-item/script.ts
  src/views/component/Navigation/corporate-footer/style.less
  src/views/component/Navigation/corporate-footer/template.html
  src/views/component/Navigation/corporate-footer/variations/1/demo.html
  src/views/component/Social/social-media/comment.md
  src/views/component/Social/social-media/index.jade
  src/views/component/Social/social-media/script.ts
  src/views/component/Social/social-media/style.less
  src/views/component/Social/social-media/template.html
  src/views/component/Social/social-media/variations/1/comment.md
  src/views/component/Social/social-media/variations/1/demo.html
  src/views/component/Social/social-media/variations/1/index.jade
  src/views/component/Social/social-media/variations/1/script.ts
  src/views/component/Social/social-media/variations/1/style.less
  src/views/component/Social/social-media/variations/1/template.html
  src/views/development.html
Labels: New Feature

#49 CUI light renders errors in console
  src/global/ts/core.ts
Labels: Bug

#53 More item not working in ie
  src/components/main-navigation/script.ts
Labels: Bug

#50 We want to be able to check CUI version
  gulpfile.js
  package.json
  src/global/ts/core.ts
Labels: Improvement

#54 Added back License agreement
  LICENSE.txt
Labels: Bug

#18 hamburger menu not visible
  src/components/corporate-header/style.less
Labels: Bug

#52 Main-nav throws exceptions
  demo/components.html
  src/components/corporate-header/script.ts
  src/components/corporate-header/template.html
  src/components/main-navigation/script.ts
Labels: Improvement

#57 Extra callback casuing issues
  src/global/ts/helpers.ts
Labels: Improvement

#61 Mobile menu bugs when show after scrolled down
  src/components/main-navigation/script.ts
  src/components/main-navigation/style.less
Labels: Bug

#1 Section padding for Public
  src/components/main-content/style.less
  src/global/less/corporate-ui/custom-classes/general.less
Labels: Improvement
