Repository scania/corporate-ui, pull requests merged in 2018-07, with the labels that each got.

#67 Bootstrap native missing dynamic init support
  src/global/ts/core.ts
Labels: Improvement, New Feature

#65 Add component info to cui
  demo/components.html
  gulpfile.js
  src/global/ts/core.ts
Labels: Improvement, New Feature

#70 Add a toggler for parent items in main nav for mobile mode
  src/components/corporate-footer/style.less
  src/components/main-content/style.less
  src/components/main-navigation/script.ts
  src/components/main-navigation/style.less
  src/components/navbar/nav-item/script.ts
  src/components/navbar/nav-item/style.less
  src/components/navbar/nav-item/template.html
  src/global/less/corporate-ui/navigation.less
Labels: Bug, Improvement

#71 Fix for bug in nav-item with mode-toggler
  src/components/navbar/nav-item/style.less
Labels: Bug

#2 Corproate should have a scroll mode for main-content
  demo/examples/flexbox.html
  src/components/main-content/script.ts
  src/components/main-content/style.less
  src/components/main-navigation/script.ts
  src/components/main-navigation/style.less
Labels: Bug, New Feature

#66 We need to have support for dealer logo
  demo/examples/dealer.html
  src/components/corporate-header/script.ts
  src/components/corporate-header/style.less
  src/components/corporate-header/template.html
Labels: New Feature

#72 removed package-lock.json file
  package-lock.json
Labels: Improvement

#75 Improvement for disabled checkbox
  demo/examples/Bootstrap/forms.html
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#76 Fix for disabled cursor on radio buttons
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#77 Fixes a bug with custom checkboxes
  src/global/less/corporate-ui/forms.less
Labels: Bug

#74 Removed background color on Hamburger:focus
  src/global/less/corporate-ui/navigation.less
Labels: Improvement

#78 New version number
  package.json
Labels: Improvement

#80 Navigation glitches on click in desktop mode
  src/components/navbar/nav-item/script.ts
Labels: Bug

#79 Fixed jump on focus border .custom-select
  src/global/less/corporate-ui/buttons.less
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#82 Icon fixes for mobile navigation
  src/global/less/corporate-ui/navigation.less
Labels: Bug

#83 Fixed buttons padding
  src/global/less/corporate-ui/buttons.less
Labels: Improvement

#97 Bootstrap text-alignments was overwritten by P and .app p
  src/global/less/corporate-ui/typography.less
Labels: Improvement

#100 Added gray border left of Scania Symbol - for mobile
  src/global/less/corporate-ui/navigation.less
Labels: Improvement

#99 Moved some components that isn't in jade structure out of the library
  src/components/article-grid/article-grid.html
  src/components/article-grid/variation-1.html
  src/components/basic-table/table.html
  src/components/basic-table/variation-1.html
  src/components/decisions-tool/decisions-tool.html
  src/components/decisions-tool/variation-1.html
  src/components/find-a-dealer-teaser/index.jade
  src/components/find-a-dealer-teaser/style.less
  src/components/find-a-dealer-teaser/template.html
  src/components/fullscreen/script.ts
  src/components/map-card/index.jade
  src/components/news-and-events-listing/news-and-events-listing.html
  src/components/news-and-events-listing/variation-1.html
  src/components/panel-grid/iron-resizable-behavior/CONTRIBUTING.md
  src/components/panel-grid/iron-resizable-behavior/README.md
  src/components/panel-grid/iron-resizable-behavior/bower.json
  src/components/panel-grid/iron-resizable-behavior/demo/index.html
  src/components/panel-grid/iron-resizable-behavior/demo/src/x-app.html
  src/components/panel-grid/iron-resizable-behavior/index.html
  src/components/panel-grid/iron-resizable-behavior/iron-resizable-behavior.html
  src/components/panel-grid/iron-resizable-behavior/test/basic.html
  src/components/panel-grid/iron-resizable-behavior/test/index.html
  src/components/panel-grid/iron-resizable-behavior/test/iron-resizable-behavior.html
  src/components/panel-grid/iron-resizable-behavior/test/test-elements.html
  src/components/panel-grid/panel-grid.html
  src/components/panel-grid/variation-1.html
  src/components/panel-grid/variation-2.html
  src/components/product-specification/product-specification.html
  src/components/product-specification/variation-1.html
  src/components/quote/quote.html
  src/components/quote/variation-1.html
  src/components/quote/variation-2.html
  src/components/rich-text-table/js/control-item.html
  src/components/rich-text-table/rich-text-table.html
  src/components/rich-text-table/variation-1.html
  src/components/rich-text-table/variation-2.html
  src/components/rich-text-table/variation-3.html
  src/components/social-conversation/social-conversation.html
  src/components/social-conversation/variation-1.html
  src/components/sticky-toolbar/sticky-toolbar.html
  src/components/sticky-toolbar/variation-1.html
Labels: Bug, Improvement

#101 Update README.md
  README.md
Labels: Improvement

#84 Adjustments to Heights - Buttons, Inputs and Nav Pills
  src/global/less/corporate-ui/buttons.less
  src/global/less/corporate-ui/forms.less
  src/global/less/corporate-ui/input-groups.less
  src/global/less/corporate-ui/navigation.less
Labels: Improvement
