Repository scania/corporate-ui, pull requests merged in 2018-05, with the labels that each got.

#3 Limit items in main-nav and add More
  src/views/component/Navigation/main-navigation/script.ts
  src/views/component/Navigation/main-navigation/style.less
  src/views/component/Navigation/main-navigation/template.html
  src/views/template/Examples/angular-navigation3.html
Labels: enhancement

#16 Readme updates
  README.md
Labels: enhancement

#25 Remove top border from striped table
  src/less/corporate-ui/tables.less
Labels: Improvement

#21 Refactoring labels
  src/less/corporate-ui/badges-labels.less
Labels: Improvement

#20 Remove table th uppercase
  src/less/corporate-ui/tables.less
Labels: Improvement

#19 Main navigation height issue on resize
  src/views/component/Navigation/main-navigation/script.ts
Labels: bug

#4 Changed active event trigger to tap
  src/views/component/Bootstrap/navbar/nav-item/script.ts
  src/views/component/Navigation/fullscreen/script.ts
Labels: bug

#17 Footer shows empty dropdown container
  src/views/component/Navigation/corporate-footer/script.ts
  src/views/component/Navigation/corporate-footer/template.html
Labels: bug

#22 form fixes, Changes for disables checkboxes
  src/less/corporate-ui/forms.less
  src/views/template/Bootstrap/forms.html
Labels: bug
