Repository scania/corporate-ui, pull requests merged in 2018-09, with the labels that each got.

#166 Added handling for changing year in the copyright text
  src/components/corporate-footer/script.ts
Labels: Improvement

#168 Main navigation dynamic items and more item fix
  demo/examples/more-dynamic.html
  demo/examples/more-dynamic2.html
  demo/examples/more.html
  src/components/main-navigation/script.ts
  src/components/main-navigation/style.less
  src/components/main-navigation/template.html
Labels: Bug, Improvement

#167 Hiding c-fullscreen from mobile menu (footer and header)
  src/components/corporate-footer/style.less
  src/components/corporate-header/style.less
Labels: Improvement

#169 change version number
  package.json
Labels: Improvement

#171 Script error in more items
  src/components/main-navigation/script.ts
  src/components/main-navigation/style.less
  src/components/main-navigation/template.html
Labels: Bug

#183 btn active box-shadow removed
  src/global/less/corporate-ui/buttons.less
Labels: Improvement

#179 border color fixed for table-panel
  src/global/less/corporate-ui/custom-classes/tables.less
Labels: Improvement

#188 Labels in forms font-size changed
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#187 Support for indexing on main nav items
  demo/examples/more-dynamic2.html
  src/components/main-navigation/script.ts
  src/components/main-navigation/style.less
  src/components/main-navigation/template.html
  src/components/navbar/nav-item/style.less
Labels: Improvement, New Feature

#190 Mobile navigation scroll not working
  src/components/corporate-header/script.ts
  src/components/main-content/style.less
  src/components/main-navigation/style.less
Labels: Bug, Improvement

#195 nav-pills height increased
  src/global/less/corporate-ui/navigation.less
  src/global/less/corporate-ui/typography.less
Labels: Improvement

#196 Version number changed
  gulpfile.js
  package.json
Labels: Improvement

#209 margin-bottom added for c-page-header
  src/global/less/corporate-ui/custom-classes/page-header.less
Labels: Improvement

#208 pagination background changed to transparant from white
  src/global/less/corporate-ui/pagination.less
Labels: Improvement

#207 Article paragraph inherit correct font-size
  src/global/less/corporate-ui/typography.less
  src/global/less/corporate-ui/variables.less
Labels: Improvement

#206 Button size increased, md(default) ,sm and lg increased padding in app
  src/global/less/corporate-ui/buttons.less
Labels: Improvement

#212 Bug/radio button fix
  demo/examples/Bootstrap/forms.html
  src/global/less/corporate-ui/custom-classes/checkboxes.less
  src/global/less/corporate-ui/custom-classes/index.less
  src/global/less/corporate-ui/custom-classes/radio-buttons.less
  src/global/less/corporate-ui/forms.less
  src/global/less/corporate-ui/input-groups.less
  src/global/less/corporate-ui/mixins.less
Labels: Bug, Improvement

#210 Compensating for wide container padding (15+15)
  src/global/less/corporate-ui/common.less
Labels: Improvement

#211 Add data support for secondary items
  demo/examples/more-dynamic2.html
  src/components/corporate-header/template.html
  src/components/main-navigation/script.ts
  src/components/main-navigation/style.less
  src/components/main-navigation/sub-navigation/style.less
  src/components/main-navigation/template.html
  src/components/navbar/nav-item/style.less
Labels: Bug, Improvement, New Feature

#215 3 small fixes
  src/global/less/corporate-ui/button-groups.less
  src/global/less/corporate-ui/custom-classes/tables.less
  src/global/less/corporate-ui/dropdowns.less
Labels: Improvement

#217 Revamp of current validation states(colors, background)
  src/global/less/corporate-ui/feedback.less
Labels: Improvement

#219 Updated local dev instructions
  README.md
Labels: Improvement, Question

#222 Change colors on default input and disabled input
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#223 improve login component
  demo/examples/login.html
  src/components/login/form-field/script.ts
  src/components/login/form-field/style.less
  src/components/login/form-field/template.html
  src/components/login/script.ts
  src/components/login/style.less
  src/components/login/template.html
Labels: Improvement

#205 Version number update
  package.json
Labels: Improvement

#231 added the correct border-color for panel-heading
  src/global/less/corporate-ui/mixins.less
Labels: Bug

#237 Scania Sans Semi Condensed instead of Scania Sans
  src/global/less/corporate-ui/typography.less
Labels: Improvement

#243 Added Font Awesome 5 but are keeping version 3 for some time
  src/global/less/corporate-ui.less
Labels: New Feature

#240 Main nav using data not working
  src/components/main-navigation/template.html
Labels: Bug

#241 More item triggers rerender
  src/components/main-navigation/style.less
  src/components/main-navigation/template.html
  src/components/navbar/nav-item/style.less
Labels: Bug

#246 Improvement/css fine tuning
  src/global/less/corporate-ui/buttons.less
  src/global/less/corporate-ui/custom-classes/buttons.less
  src/global/less/corporate-ui/mixins.less
Labels: Improvement

#245 Auth component not sending data
  demo/examples/login.html
  src/components/login/script.ts
  src/components/login/template.html
Labels: Improvement, New Feature

#242 Button spacing fixes
  src/global/less/corporate-ui/button-groups.less
  src/global/less/corporate-ui/buttons.less
Labels: Improvement

#244 New header sizes for h1 and h2 when used in c-page-header and h1 in panel-body
  src/global/less/corporate-ui/custom-classes/page-header.less
  src/global/less/corporate-ui/panels-wells.less
Labels: Improvement

#249 table-panel border-collapse
  src/global/less/corporate-ui/custom-classes/tables.less
Labels: Improvement

#248 Improved navigation implementation
  demo/examples/more-dynamic2.html
  demo/examples/more.html
  src/components/main-navigation/template.html
  src/components/navbar/nav-item/script.ts
Labels: Bug, Improvement, New Feature

#253 version number changed
  package.json
Labels: Improvement

#257 Improved main-nav and nav-item handling
  demo/examples/angular-navigation2.html
  demo/examples/more-dynamic2.html
  src/components/corporate-header/script.ts
  src/components/main-navigation/script.ts
  src/components/main-navigation/template.html
  src/components/navbar/nav-item/script.ts
  src/components/navbar/nav-item/style.less
Labels: Bug, Improvement, Major change

#261 Added c-social-media as a dependency for c-corporate-footer
  demo/index.html
  src/components/corporate-footer/index.jade
Labels: Improvement
