Repository scania/corporate-ui, pull requests merged in 2018-12, with the labels that each got.

#418 Improvement/height for input group
  src/global/less/corporate-ui/custom-classes/checkboxes.less
  src/global/less/corporate-ui/mixins.less
Labels: Improvement

#417 Issue with variations on main componetns
  src/global/ts/core.ts
  src/global/ts/helpers.ts
Labels: Bug

#416 Add support for dynamic bs tooltip support
  src/global/ts/core.ts
Labels: New Feature

#409 Main-nav more item when fullscreen toggle
  src/components/fullscreen/script.ts
  src/components/fullscreen/template.html
  src/components/main-navigation/script.ts
Labels: Bug

#367 Added a global data store
  demo/examples/store-example.html
  demo/examples/store.html
  demo/testing/testing.html
  gulpfile.js
  package.json
  src/components/main-navigation/script.ts
  src/global/ts/core.ts
  src/global/ts/corporate-ui.ts
  src/global/ts/helpers.ts
  src/global/ts/reducerRegistry.ts
  src/global/ts/store.ts
Labels: New Feature

#427 Mobile nav not rendered
  demo/examples/more-dynamic2.html
  src/components/main-navigation/script.ts
Labels: Bug

#425 Added styling for :focus and :active states in Corporate Header
  src/components/corporate-header/style.less
Labels: Improvement

#430 Added styling for :focus and :active states in Corporate Footer
  src/components/corporate-footer/style.less
Labels: Improvement

#385 Improvement/file upload fix
  demo/examples/file-upload.html
  src/components/file-upload/comment.md
  src/components/file-upload/file-icon/comment.md
  src/components/file-upload/file-icon/variations/1/demo.html
  src/components/file-upload/script.ts
  src/components/file-upload/style.less
  src/components/file-upload/template.html
  src/components/file-upload/variations/1/comment.md
  src/components/file-upload/variations/1/demo.html
Labels: Improvement

#433 Improvements for main-navigation
  gulpfile.js
  src/components/main-content/style.less
  src/components/main-navigation/style.less
  src/components/main-navigation/sub-navigation/style.less
  src/components/main-navigation/variations/1/style.less
  src/components/main-navigation/variations/2/style.less
  src/components/navbar/nav-item/script.ts
  src/components/navbar/nav-item/style.less
Labels: Improvement

#435 Added dynamic support for setting attrs
  demo/examples/more-dynamic2.html
  src/components/navbar/nav-item/script.ts
Labels: Improvement

#437 Info button in .btn-group is currently inversed. More like the defaul…
  src/global/less/corporate-ui/button-groups.less
Labels: Improvement
