Repository scania/corporate-ui, pull requests merged in 2018-10, with the labels that each got.

#265 Smaller Social Icons For App Footer
  src/components/social-media/style.less
Labels: Improvement

#282 Fixing nav-pills and btn-block
  src/global/less/corporate-ui/buttons.less
  src/global/less/corporate-ui/navigation.less
Labels: Improvement

#281 Small icons in table header.
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#279 Improvement/forms inputs styling
  demo/examples/Bootstrap/forms-example.html
  demo/examples/Bootstrap/forms.html
  src/global/less/corporate-ui/forms.less
  src/global/less/corporate-ui/variables.less
Labels: Improvement

#284 removed icon on checkbox disabled
  src/global/less/corporate-ui/mixins.less
Labels: Improvement

#283 Version number changed
  package.json
Labels: Improvement

#276 Update bug issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Improvement

#287 Issue Bug Report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Improvement

#264 Feature/components analytics
  package.json
  src/components/alert/script.ts
  src/components/component.jade
  src/components/contact-us/script.ts
  src/components/corporate-footer/script.ts
  src/components/corporate-header/script.ts
  src/components/dashboard/script.ts
  src/components/find-a-dealer-teaser/script.ts
  src/components/fullscreen/script.ts
  src/components/highcharts/script.ts
  src/components/list-group/script.ts
  src/components/login/script.ts
  src/components/main-content/script.ts
  src/components/main-hero/script.ts
  src/components/main-navigation/script.ts
  src/components/map-card/script.ts
  src/components/map/script.ts
  src/components/modal/script.ts
  src/components/navbar/script.ts
  src/components/rich-media/script.ts
  src/components/social-media/script.ts
  src/components/teaser/script.ts
  src/components/text-and-image/script.ts
  src/components/tiled-display/script.ts
  src/global/ts/core.ts
Labels: New Feature

#288 Added Improvement Suggestion
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement_suggestion.md
Labels: Improvement

#289 Social-media component not showing the icon
  src/components/navbar/nav-item/script.ts
  src/components/navbar/nav-item/template.html
Labels: Bug

#292 change version
  package.json
Labels: Improvement

#293 Sub-naviagation not visible in main-nav
  src/components/navbar/nav-item/template.html
Labels: Bug

#298 Sorting of nav-items in main-nav not working
  demo/examples/more-dynamic2.html
  src/components/main-navigation/script.ts
  src/components/main-navigation/template.html
Labels: Bug, Improvement

#294 Improvement/small improvs
  src/global/less/corporate-ui/typography.less
  src/global/ts/core.ts
Labels: Improvement

#295 Improvement/ Adding Bootstrap4 Cards
  src/global/less/corporate-ui/core.less
  src/global/less/corporate-ui/custom-classes/cards.less
Labels: New Feature

#300 Added travis.yml file for testing
  .travis.yml
Labels: New Feature

#305 Main-nav design update
  src/components/main-navigation/style.less
  src/global/less/corporate-ui/navigation.less
Labels: Improvement

#304 Main-navigation trigger event on sticky
  src/components/main-navigation/script.ts
Labels: New Feature

#301 Show build passing with markdown
  README.md
Labels: Improvement

#309 Support config of the More item text
  demo/examples/more-dynamic2.html
  src/components/main-navigation/script.ts
  src/components/main-navigation/template.html
Labels: New Feature

#306 No hamburger item available
  src/components/main-navigation/script.ts
  src/components/navbar/nav-item/style.less
Labels: Bug

#311 Labels and badges
  src/global/less/corporate-ui/badges-labels.less
Labels: Improvement

#303 Add support for template to nav-item
  demo/examples/more-dynamic2.html
  src/components/main-navigation/template.html
  src/components/navbar/nav-item/script.ts
  src/components/navbar/nav-item/template.html
Labels: Improvement, New Feature

#313 Improvement/form fixes
  src/global/less/corporate-ui/custom-classes/form.less
  src/global/less/corporate-ui/forms.less
  src/global/less/corporate-ui/mixins.less
  src/global/less/corporate-ui/tables.less
Labels: Improvement

#299 Updated icons to FA PRO 5
  src/components/navbar/nav-item/template.html
Labels: Improvement

#312 Basecomponent needs improvement
  src/global/ts/core.ts
Labels: Improvement

#314 Remove support for HighCharts as it does violate our licensing agreement
  package.json
  src/components/highcharts/index.jade
  src/components/highcharts/variations/1/index.jade
Labels: Improvement

#318 Remove all highchart files
  src/components/highcharts/comment.md
  src/components/highcharts/script.ts
  src/components/highcharts/style.less
  src/components/highcharts/template.html
  src/components/highcharts/variations/1/comment.md
  src/components/highcharts/variations/1/demo.html
  src/components/highcharts/variations/1/script.ts
  src/components/highcharts/variations/1/style.less
  src/components/highcharts/variations/1/template.html
Labels: Improvement

#321 Improvements/checkbox and radio button labels
  demo/examples/Bootstrap/forms-example.html
  src/global/less/corporate-ui/custom-classes/checkboxes.less
Labels: Improvement

#328 Mobile mode settings adjusted
  src/components/corporate-footer/style.less
  src/components/corporate-header/script.ts
  src/components/corporate-header/style.less
  src/components/main-navigation/script.ts
  src/components/navbar/nav-item/script.ts
Labels: Improvement

#330 Create a component for multi select
  demo/examples/select.html
  globals.d.ts
  package.json
  src/components/select/comment.md
  src/components/select/index.jade
  src/components/select/script.ts
  src/components/select/style.less
  src/components/select/template.html
  src/components/select/variations/1/comment.md
  src/components/select/variations/1/demo.html
  src/components/select/variations/1/index.jade
  src/components/select/variations/1/script.ts
  src/components/select/variations/1/style.less
  src/components/select/variations/1/template.html
Labels: Improvement, New Feature

#325 Improvements for .app p.lead and .page-header
  src/global/less/corporate-ui/custom-classes/page-header.less
  src/global/less/corporate-ui/typography.less
Labels: Improvement

#334 - Input group with checkbox, radiobutton and button
  src/global/less/corporate-ui/custom-classes/checkboxes.less
  src/global/less/corporate-ui/input-groups.less
  src/global/less/corporate-ui/mixins.less
Labels: Improvement

#339 Fixed calc() and fixed responsive width
  src/global/less/corporate-ui/modal.less
Labels: Bug

#338 Improvements/checkbox and radio button labels
  src/global/less/corporate-ui/custom-classes/checkboxes.less
Labels: Improvement

#337 input-sm and lg form-control and select
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#336 Sub-navigation trigger active on first item
  src/components/navbar/nav-item/script.ts
Labels: Bug

#333 Expand collapse in main-nav on mobile
  src/components/main-navigation/style.less
  src/components/navbar/nav-item/style.less
Labels: Bug

#341 modal content top added for better position
  src/global/less/corporate-ui/modal.less
Labels: Bug

#340 Calc fix
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#335 c-cookie-message component
  package.json
  src/components/cookie-message/comment.md
  src/components/cookie-message/index.jade
  src/components/cookie-message/script.ts
  src/components/cookie-message/style.less
  src/components/cookie-message/template.html
  src/components/cookie-message/variations/1/comment.md
  src/components/cookie-message/variations/1/demo.html
  src/components/cookie-message/variations/1/index.jade
  src/components/cookie-message/variations/1/script.ts
  src/components/cookie-message/variations/1/style.less
  src/components/cookie-message/variations/1/template.html
Labels: New Feature

#329 Add dropdown support to all nav levels
  demo/examples/angular-basic-template.html
  demo/examples/more-dynamic2.html
  src/components/main-navigation/template.html
  src/components/navbar/nav-item/style.less
  src/components/navbar/nav-item/template.html
Labels: Improvement, New Feature

#342 Improvement/modal fullscreen
  src/global/less/corporate-ui/modal.less
Labels: Improvement

#344 Simplify select2 workflow
  demo/examples/select2.html
  src/global/less/corporate-ui.less
  src/global/less/corporate-ui/custom-classes/index.less
  src/global/less/corporate-ui/custom-classes/select2.less
Labels: Improvement

#322 Margin and size changes in c-social-media in c-corporate-footer
  src/components/corporate-footer/style.less
  src/components/social-media/style.less
Labels: Improvement

#345 Add login component documentation
  src/components/login/variations/1/comment.md
Labels: Improvement, UX Library

#324 Pixel tuning for panels with tables and panels with accordions
  src/global/less/corporate-ui/panels-wells.less
Labels: Improvement

#346 Add for multiple attribute in select basic.
  src/global/less/corporate-ui/custom-classes/select2.less
  src/global/less/corporate-ui/forms.less
Labels: Improvement

#320 Create a pull-request template
  PULL_REQUEST_TEMPLATE.md
Labels: Improvement

#349 Expand collapse in main-nav not working
  src/components/navbar/nav-item/style.less
Labels: Bug

#351 Addes initial user-profile classes to Corporate UI
  src/global/less/corporate-ui/custom-classes/index.less
  src/global/less/corporate-ui/custom-classes/user-profile.less
Labels: Improvement

#352 Short-name flag not working in header
  src/components/corporate-header/template.html
Labels: Bug

#355 3.4.0
  package.json
Labels: Improvement

#354 Improvement/small fixes
  src/global/less/corporate-ui/dropdowns.less
  src/global/less/corporate-ui/modal.less
Labels: Improvement

#358 Improvement/select2 disabled
  src/global/less/corporate-ui/custom-classes/checkboxes.less
  src/global/less/corporate-ui/custom-classes/select2.less
Labels: Improvement

#357 Improvement/small fixes add ons
  src/global/less/corporate-ui/dropdowns.less
  src/global/less/corporate-ui/modal.less
Labels: Improvement

#359 Sub-nav is not getting rendered in main-nav
  src/components/navbar/nav-item/script.ts
Labels: Bug

#360 Fixes for modal
  src/global/less/corporate-ui/modal.less
Labels: Improvement

#275 Remove background image for input checkbox disabled
  src/global/less/corporate-ui/mixins.less
Labels: Improvement, Inactive
