Repository scania/corporate-ui, pull requests merged in 2019-01, with the labels that each got.

#438 Version number changed 3.5.1
  package.json
Labels: Improvement

#434 Fixed text overflow of caret (arrow)
  src/global/less/corporate-ui/forms.less
  src/global/less/corporate-ui/tables.less
Labels: Bug

#419 Handle condition if monitoring set to false
  src/components/component.jade
  src/global/ts/core.ts
Labels: Improvement

#441 Add handling for active sub items
  src/components/main-navigation/sub-navigation/script.ts
Labels: Improvement

#440 Select2 multiselect not visible
  src/global/less/corporate-ui/custom-classes/select2.less
Labels: Bug, FMP*

#439 cookie component modal and mobile view
  demo/examples/Bootstrap/panels.html
  src/components/cookie-message/comment.md
  src/components/cookie-message/script.ts
  src/components/cookie-message/style.less
  src/components/cookie-message/template.html
Labels: Improvement

#451 Bootstrap triggers does not work in FF 64
  src/components/corporate-header/script.ts
  src/components/main-navigation/script.ts
  src/components/navbar/nav-item/script.ts
Labels: Bug
