Repository scania/corporate-ui, pull requests merged in 2019-12, with the labels that each got.

#478 Bug with max-height in mobile navigation
  demo/examples/more-dynamic2.html
  src/components/main-navigation/style.less
Labels: Bug

#490 Bumped version
  package.json
Labels: New Feature

#512 Changed project references
  CONTRIBUTING.md
  package-lock.json
  package.json
  readme.md
Labels: Improvement

#513 Fix issue in chrome from crashing
  src/global/ts/core.ts
Labels: bug

#514 Bump version
  package.json
Labels: Improvement

#516 Improvement/script for cdn solution
  package.json
  readme.md
  src/helpers/cdn.js
  stencil.config.ts
Labels: Improvement

#517 Improvement - Update travis.yml and package-lock
  .travis.yml
  package-lock.json
Labels: Improvement

#515 Improvement/added developing components
  CONTRIBUTING.md
  readme.md
Labels: Improvement

#518 Bump version
  package-lock.json
  package.json
Labels: Improvement

#519 Bump version
  package-lock.json
  package.json
Labels: Improvement

#524 Bump version name for production
  package-lock.json
  package.json
Labels: Improvement
