Repository scania/corporate-ui, pull requests merged in 2019-04, with the labels that each got.

#459 Added support for items in corporate footer
  demo/examples/more-dynamic2.html
  src/components/corporate-footer/script.ts
  src/components/corporate-footer/template.html
Labels: New Feature

#412 Update for PULL_REQUEST_TEMPLATE template with more information
  PULL_REQUEST_TEMPLATE.md
Labels: Improvement

#444 Fixed hight issue that occurd when many items where picked and didn't fit.
  src/global/less/corporate-ui/custom-classes/select2.less
  src/global/less/corporate-ui/forms.less
Labels: Bug

#467 Update package.json
  package.json
Labels: Improvement

#426 fix moving footer on IE when hover on nav item
  demo/index.html
  src/components/corporate-footer/style.less
  src/components/corporate-footer/template.html
Labels: Bug

#468 Fix for basic select option
  demo/examples/Bootstrap/forms.html
  src/global/less/corporate-ui/forms.less
Labels: Improvement
