Repository scania/corporate-ui, pull requests merged in 2020-11, with the labels that each got.

#594 Improvement/upgrade stencil 2
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  src/components/content/content.spec.ts
  src/components/content/content.tsx
  src/components/cookie/cookie.tsx
  src/components/dealer-header/dealer-header.spec.ts
  src/components/dealer-header/dealer-header.tsx
  src/components/dropdown/dropdown.tsx
  src/components/footer/footer.spec.ts
  src/components/footer/footer.tsx
  src/components/global-style/global-style.tsx
  src/components/header/header.spec.ts
  src/components/header/header.tsx
  src/components/icon/icon.tsx
  src/components/modal/modal.tsx
  src/components/navigation/navigation.spec.ts
  src/components/navigation/navigation.tsx
  src/components/table/table.tsx
  src/components/theme/theme.tsx
  src/global.spec.ts
  src/global.ts
  src/helpers/cdn.js
  src/helpers/index.js
  src/helpers/themeStyle.ts
  src/store.ts
  stencil.config.ts
Labels: Improvement

#588 Bug with dot in nested data for c-table
  src/components/table/table.tsx
Labels: bug

#597 Feature/bump version 4.2.0-1
  package-lock.json
  package.json
Labels: Feature

#595 Feature - 4px base unit
  src/components/code-sample/code-sample.scss
  src/components/cookie/cookie.scss
  src/components/footer/footer.scss
  src/components/table/table.scss
  src/components/theme/theme.scss
Labels: Feature

#600 Fixing display issues for the navbar within c-header
  src/components/header/header.scss
  src/components/navigation/navigation.scss
Labels: bug

#601 Bumped version 4.2.0-2
  package-lock.json
  package.json
Labels: Feature
