Repository scania/corporate-ui, pull requests merged in 2020-01, with the labels that each got.

#525 Fix code-sample duplicate item in ie
  src/components/code-sample/code-sample.scss
  src/components/code-sample/code-sample.tsx
Labels: Improvement

#526 Refactored FOUC part
  src/components.scss
  src/components/global-style/global-style.scss
  src/components/theme/theme.scss
  src/helpers/index.js
Labels: Improvement

#529 Feature - bump version pre release corporate-ui
  package-lock.json
  package.json
Labels: Feature

#531 Feature - bump version
  package-lock.json
  package.json
Labels: Feature

#533 Fix FoUC visibility style order
  src/helpers/index.js
Labels: bug

#534 Bump version 4.0.2
  package-lock.json
  package.json
Labels: Improvement

#535 Fixed rules order in IE
  src/components/global-style/global-style.scss
Labels: bug

#536 Add prod config
  package-lock.json
  package.json
  stencil.config.ts
Labels: Feature

#541 bump version
  package-lock.json
  package.json
Labels: Feature
