Repository scania/corporate-ui, pull requests merged in 2020-05, with the labels that each got.

#559 Optimization distribution package
  package-lock.json
  package.json
  src/global.ts
Labels: Improvement

#561 Bumped version
  package-lock.json
  package.json
Labels: Feature

#563 Bug- fallback colour for IE added in code-example
  src/components/code-sample/code-sample.scss
  src/components/code-sample/code-sample.tsx
Labels: bug
